### ISSUE TITLE
Download link not working

### ISSUE THREAD

**Issue by xDreamms** [0xFireball/ModPhuserEx#16]
https://ci.appveyor.com/api/projects/0xFireball/modphuserex/artifacts/Build/ModPhuserEx_bin.zip  not working

**Comment by HoLLy-HaCKeR** [comment]
Build it yourself. AppVeyor artifacts only get stored for 6 months.

**Comment by xDreamms** [comment]
> Build it yourself. AppVeyor artifacts only get stored for 6 months.

I get errors that I can't fix it.... Can you send me binaries pls ? I don't understand developers who don't release binaries.... Why do I have to build ?

**Comment by HoLLy-HaCKeR** [comment]
Developers have no obligation to provide support or even guarantee that their tools will be useful to you. This code is most likely provided as is, and if you can't get it to work for you, tough luck. I suggest learning how to code or at least how to google.

**Comment by xDreamms** [comment]
> Developers have no obligation to provide support or even guarantee that their tools will be useful to you. This code is most likely provided as is, and if you can't get it to work for you, tough luck. I suggest learning how to code or at least how to google.

I know how to code and how to google and I suggest you to being human and helpful person.
