### ISSUE TITLE
how to build?

### ISSUE THREAD

**Issue by ohacn** [0xFireball/ModPhuserEx#2]
Build.cmd get error

“D:\ModPhuserEx\Confuser2.sln”(默认目标) (1) ->
“D:\ModPhuserEx\Confuser.Core\Confuser.Core.csproj”(默认目标) (2) ->
(CoreCompile 目标) ->
  Helpers\InjectHelper.cs(242,25): error CS0246: 未能找到类型或命名空间名称“ImportResolver”(是否缺少 using 指令或程序 集引用?) [D:\ModPhuserEx\Co
nfuser.Core\Confuser.Core.csproj]

ImportResolver can't find

**Comment by 0xFireball** [comment]
Did you restore `dnlib`? Make sure you run `git submodule update --init --recursive`.

I will add build instructions to the readme.
