### ISSUE TITLE
Running ModPhuserEx from a command line

### ISSUE THREAD

**Issue by sammynage** [0xFireball/ModPhuserEx#4]
So, I downloaded it from https://0xfireball.github.io/ModPhuserEx/ (which is awesome!)

Is there anyway to run it from a command line? Just trying to script out a build process, and right now the gui pops up.

I was wondering if there was some way to run it silently.  

thanks!

**Comment by 0xFireball** [comment]
You should be able to run `Confuser.CLI`, which I just noticed is not included in the package build. Right now you can build the project from source or wait for me to update the build script to include the CLI tool (I'll get to it soon).

ModPhuserEx's is based on ConfuserEx; this project exists to continue development as the original project has been abandoned by the original author.

**Comment by 0xFireball** [comment]
@sammynage build script has been updated. The latest development build from the website (https://0xfireball.github.io/ModPhuserEx/#download) includes `ModPhuserEx.CLI` (It's just a renamed ConfuserEx CLI since the fork).

**Comment by sammynage** [comment]
Thanks a bunch!
